### ISSUE TITLE
Service is down?

### ISSUE THREAD

**Issue by c01nd01r** [CyberLight/caninclude#22]
![Снимок экрана 2020-12-11 в 23 00 26](https://user-images.githubusercontent.com/3511312/101949477-b6d6d380-3c04-11eb-9e85-fb0837a72826.png)

**Comment by CyberLight** [comment]
Thanks for your reaction. I don't know why this is, perhaps glitch.com is changing the behavior of free projects. I will need to monitor the status of the site for a while.

**Comment by CyberLight** [comment]
The site is now up and running
