### ISSUE TITLE
Can <video> tag be within <audio> tag? (And vice versa.)

### ISSUE THREAD

**Issue by Zegnat** [CyberLight/caninclude#87]
Currently the site is unsure ("I doubt") for both [video as child](https://caninclude.glitch.me/can/include/?child=video&parent=audio) and [as parent](https://caninclude.glitch.me/can/include/?child=audio&parent=video). The correct answer to the question is a definitive **no**.

It looks like the site is doubting because of the transparent content model:

> Because the parent `<audio/>` tag has the <b>Transparent</b> content option and the ability to nest the tag is not fully understood.

But when we read the actual content model section for these tags, we will find the following:

> <i>[...]</i> then transparent, but with no media element descendants.

The only media elements in the HTML spec today are `video` and `audio`, see [4.8.12 Media elements](https://html.spec.whatwg.org/multipage/media.html#media-elements). So we can definitively say that even though these elements have a transparent content model they can never be nested inside eachother.

I am not sure how this could be parsed out of the spec in an easy way. It might not be possible. But thought I would leave it here as a note anyway. Thanks for this cool project!

**Comment by CyberLight** [comment]
Hi @Zegnat !
Thank you for your feedback! 
It's so cool that reviews come from those who use the site!

Based on this feedback as well as past experience and bugs, I am preparing version 2.0 in which I think I can fix the problems described in other open issues. There will be a different approach in evaluating the possibility of including a tag in a tag.

**Comment by Zegnat** [comment]
Awesome! Definitely going to keep my eyes out for the 2.0 then.

**Comment by Zegnat** [comment]
The new 2.0 shows "No, you can't!" for `video` elements inside `audio` elements and vice-versa. Closing this as fixed 🎉
