### ISSUE TITLE
site doesn't work

### ISSUE THREAD

**Issue by NaturelLaurent** [CyberLight/caninclude#90]
failed to start application on caninclude.glitch.me

This is most likely because your project has a code error.
Check your project logs, fix the error and try again.

**Comment by Yrsafam** [comment]
Hi! I have too problem.
![изображение](https://user-images.githubusercontent.com/60210785/174992566-697f3704-751d-4adc-8ce5-5e9e595ad086.png)

**Comment by CyberLight** [comment]
Fixed )
